### ISSUE TITLE
盒模型分为哪些类型？有什么区别？

### ISSUE THREAD

**Issue by BlueMiao10** [BlueMiao10/CV#35]
盒模型分为两种：标准盒模型：content-box    IE盒模型：border-box
区别：
标注盒模型顾名思义，它设置的width和height指的是content的宽和高
IE盒模型，它设置的width和height还包括内边距padding和border

一般在css问价开头将盒模型重置为IE盒模型，为了计算方便
采用的语法如下：
```css
html{
   box-sizing:border-box;
}
/*这句话的目的主要是用来当有类似弹窗效果需要content-box时，我们只需要更改父亲的类型，他的自带可以继承，不需要再重新更改*/
*,*::biefore,*::after{
  box-sizing:inherit;
}
```

题目来自饥人谷
