### ISSUE TITLE
如何使用浮动实现两栏和三栏布局？给出范例

### ISSUE THREAD

**Issue by BlueMiao10** [BlueMiao10/CV#43]
- 实现两栏布局
```html
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="index.css" />
    <title>Static Template</title>
  </head>
  <body>
    <nav class="a">这是导航栏</nav>
    <main class="c">这是主要部分</main>
  </body>
</html>
```

```css
body {
  height: 500px;
}

.a {
  width: 100px;
  background-color: red;
  height: 100%;
  float: left;
  text-align: center;
}

.c {
  height: 1000px;
  background-color: blue;
  text-align: center;
  margin-left: 120px;
}
```

- 三栏布局
```html
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="index.css" />
    <title>Static Template</title>
  </head>
  <body>
    <nav class="a">这是导航栏</nav>
    <aside class="b">这是侧边广告栏</aside>
    <main class="c">这是主要部分</main>
  </body>
</html>
```

```css
body {
  height: 500px;
}

.a {
  width: 100px;
  background-color: red;
  height: 100%;
  float: left;
  text-align: center;
}

.b {
  width: 100px;
  background-color: red;
  height: 100%;
  float: right;
  text-align: center;
}

.c {
  height: 1000px;
  background-color: blue;
  text-align: center;
  margin-left: 120px;
  margin-right: 120px;
}

```
题目来自饥人谷
