### ISSUE TITLE
使用grid布局实现经典两栏布局

### ISSUE THREAD

**Issue by BlueMiao10** [BlueMiao10/CV#44]
```html
<body>
  <header>header</header>
  <aside>aside</aside>
  <main>main</main>
  <footer>footer</footer>
</body>
```

```css
body{
  display:grid;
  grid:auto auto auto / 200px 1fr;
  max-width:800px;
}

header{
  background-color: red;
  grid-area:1 / 1 / 2 / 3;
  text-align:center;
}

aside{
  background-color: yellow;
  grid-area:2 / 1 / 3 / 2;
  height:500px;
   
}

main{
  background-color: pink;
  grid-area:2 / 2 / 3 / 3;
}

footer{
  background-color:green;
  grid-area:3 / 1 / 4 / 3; 
  text-align:center;
}
```

题目来自饥人谷
