### ISSUE TITLE
使用flex布局实现三列等分效果

### ISSUE THREAD

**Issue by BlueMiao10** [BlueMiao10/CV#51]
```html
<body>
  <div class="container">
    <div class="box box1">你好</div>
    <div class="box box2">你好</div>
    <div class="box box3">你好</div>
  </div>

</body>
```

```css
.container{
  display:flex;
}

.box{
  flex-grow:1;
}

.box1{
  background-color: red;
}
.box2{
  background-color: green;
}
.box3{
  background-color: blue;
}

```

题目来自饥人谷
