### ISSUE TITLE
使用flex布局实现垂直水平居中效果

### ISSUE THREAD

**Issue by BlueMiao10** [BlueMiao10/CV#52]
```html
<body>
  <div class="container">
    <div class="box1">你好</div>
  </div>
</body>
```

```css
.container{
  display:flex;
  width:800px;
  height:800px;
  justify-content:center;
  align-items:center;
  background-color: #ccc;
}

.box1{
/*还可以使用margin：auto的方式*/
  background-color:red;
}
```

题目来自饥人谷
