### ISSUE TITLE
使用flex布局实现经典三栏布局

### ISSUE THREAD

**Issue by BlueMiao10** [BlueMiao10/CV#53]
```html
<body>
<header>这是头部</header>
<div class="container">
  <nav class="box navside">这是导航</nav>
  <main class="box content">
    <p> 出现原因：单页面应用的html是靠js生成,因为首屏需要加载很大的js文件(app.js vendor.js)，所以当网速差的时候会产生一定程度的白屏</p>
    <p>解决办法：（1)优化 webpack 减少模块打包体积，code-split 按需加载 （2）服务端渲染，在服务端事先拼装好首页所需的html（3）首页加 loading 或 骨架屏 </p>
  </main>
  <aside class="box">这是侧边栏</aside>
</div>
  <footer class="footer">这是脚部</footer>
</body>
```

```css
header{
  background-color: pink;
  text-align:center;
}

footer{
  background-color: purple;
  text-align:center;
}

.container{
  display:flex;
}


.navside{
  background-color: red;
  width:200px;
}

.content{
  background-color: #ccc;
  flex-grow:1;
  padding:10px;
}

.container>aside{
  background-color: blue;
  width:200px;
}
```

题目来自饥人谷
